name: Docker Build and Deploy - MAIN

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}
          build-args: |
            USERNAME=${{ secrets.GHCR_USERNAME }}
            TOKEN=${{ secrets.TOKEN }}

  pull-and-run-image:
    needs: build-and-push-image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        env:
          USERNAME: ${{ secrets.GHCR_USERNAME }}
          TOKEN: ${{ secrets.TOKEN }}
        with:
          host: ${{ secrets.PROD_EC2_HOST_DNS }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: USERNAME, TOKEN
          script: |
            cd infra
            sudo docker login --username $USERNAME --password $TOKEN ghcr.io
            sudo docker-compose -f docker-compose.prod.yml stop snippet-runner
            sudo docker system prune --force
            sudo docker-compose -f docker-compose.prod.yml pull snippet-runner
            sudo docker-compose -f docker-compose.prod.yml up -d snippet-runner
