name: Docker Build and Deploy - MAIN

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: printscript-10
          password: ${{ secrets.TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}-main

  pull-and-run-image:
    needs: build-and-push-image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        env:
          TOKEN: ${{ secrets.TOKEN }}
        with:
          host: ${{ secrets.DEV_EC2_HOST_DNS }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: TOKEN
          script: |
            cd infra
            sudo docker login --username printscript-10 --password $TOKEN ghcr.io
            sudo docker-compose -f docker-compose.dev.yml stop ${{ github.repository }}-main
            sudo docker system prune --force
            sudo docker-compose -f docker-compose.dev.yml pull ${{ github.repository }}-main
            sudo docker-compose -f docker-compose.dev.yml up -d ${{ github.repository }}-main
